apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxi-app
  template:
    metadata:
      annotations:
        logging.googleapis.com/logging: "true"
      labels:
        app: taxi-app
    spec:
      containers:
        - name: taxi-container
          image: musahx/taxi-app:prod-v1
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: MONGO_URI
              value: mongodb://root:root@mongo:27017
            - name: JWT_SECRET
              value: supersecretkey
            - name: EMAIL_FROM
              value: musajee10122002@gmail.com
            - name: EMAIL_PASS
              value: rrddyoeskgwwuqyc
