apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxi-app
  template:
    metadata:
      labels:
        app: taxi-app
    spec:
      containers:
        - name: taxi-container
          image: musahx/taxi-app:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: MONGO_URI
              value: mongodb+srv://musa:musa@taxi-app.ipqtcfy.mongodb.net/taxiapp?retryWrites=true&w=majority&appName=taxi-app
            - name: JWT_SECRET
              value: supersecretkey
            - name: EMAIL_FROM
              value: musajee10122002@gmail.com
            - name: EMAIL_PASS
              value: rrddyoeskgwwuqyc
